%YAML 1.0
---

# RISC OS build file to execute on https://build.riscos.online/

# Source is optional (NYI), and should be a URL to source the content from
#source: <url>

# Defines a list of jobs which will be performed.
# Only 1 job will currently be executed.
jobs:
  build:
    # Env defines system variables which will be used within the environment.
    # Multiple variables may be assigned.
    env:
      "Sys$Environment": ROBuild
      "BUILD32": 1

      # Faster building using the host toolchain
      "Alias$AMU": "HostAMU %*0"

    # Directory to change to before running script
    #dir: <working directory>

    # Commands which should be executed to perform the build.
    # The build will terminate if any command returns a non-0 return code or an error.
    script:
      - cdir Artifacts

      - echo **** Building library ****
      - dir RISCOS
      - amu export -f MakefileLib
      - copy <Exports$Dir>.Lib.LineNoise ^.Artifacts.Lib ~CVR

      - echo **** Building command line tool ****
      - amu -f MakefileExample
      - copy aif32.example ^.Artifacts.Example ~CVR
      - dir ^

      - echo **** Run tool as a test that it works ****
      - echo (disabled) /Artifacts.Example < lines.txt

      - echo **** Build the LineNoise module ****
      - dir RISCOS.module
      - amu ram
      - copy rm32.LineNoise ^.^.Artifacts.LineNoise ~CVR

    # Outputs from the build are defined in artifacts
    # These are a list of artifacts to report directories or files.
    # Only a single item is currently supported.

    # Outputs from the build are defined in artifacts
    # These are a list of artifacts to report directories or files.
    # Only a single item is currently supported.
    artifacts:
      # Each element of the artifacts should have a path key, which gives the file or
      # directory to return.
      - path: Artifacts
